name: CI – WordPress Smoke Tests (Stable)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/ci-wordpress.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: wp
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_ROOT_PASSWORD: root
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=5s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start WordPress (php-apache)
        run: |
          docker run -d --name wp \
            -e WORDPRESS_DB_HOST=127.0.0.1:3306 \
            -e WORDPRESS_DB_USER=wp \
            -e WORDPRESS_DB_PASSWORD=wp \
            -e WORDPRESS_DB_NAME=wp
