name: CI – WordPress Smoke Tests (Stable)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/ci-wordpress.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: wp
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_ROOT_PASSWORD: root
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=5s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start WordPress (php-apache)
        run: |
          docker run -d --name wp \
            -e WORDPRESS_DB_HOST=127.0.0.1:3306 \
            -e WORDPRESS_DB_USER=wp \
            -e WORDPRESS_DB_PASSWORD=wp \
            -e WORDPRESS_DB_NAME=wp \
            -p 8080:80 \
            wordpress:php8.2-apache

      - name: Prepare WordPress files (host extract + docker cp)
        run: |
          # Stop the container to release file handles
          docker stop wp

          # Download and extract WordPress on the HOST (plain URL)
          curl -sSL https://wordpress.org/latest.zip -o /tmp/wp.zip
          rm -rf /tmp/wordpress && unzip -q /tmp/wp.zip -d /tmp

          # Replace docroot with a clean copy
          docker cp /tmp/wordpress/. wp:/var/www/html/

          # Start container again
          docker start wp

      - name: Configure and install WordPress (idempotent, robust)
        run: |
          # 0) Fetch wp-cli.phar on HOST to avoid YAML/Markdown interference
          curl -sS -L https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /tmp/wp-cli.phar

          # 1) Put it in the container and verify
          docker cp /tmp/wp-cli.phar wp:/usr/local/bin/wp
          docker exec wp bash -lc 'chmod +x /usr/local/bin/wp && /usr/local/bin/wp --version || true'

          # 2) Wait for MySQL readiness inside the container
          for i in {1..60}; do
            docker exec wp bash -lc 'mysqladmin ping -h 127.0.0.1 -P 3306 -u wp -pwp >/dev/null 2>&1'
            if [ $? -eq 0 ]; then echo "MySQL ready"; break; fi
            echo "Waiting for MySQL..."; sleep 2
          done

          # 3) Helper to always pass --allow-root and the path
          WP="/usr/local/bin/wp --allow-root --path=/var/www/html"

          # 4) Fresh config then create (idempotent)
          docker exec wp bash -lc 'rm -f /var/www/html/wp-config.php'
          docker exec wp bash -lc "$WP config create --dbname=wp --dbuser=wp --dbpass=wp --dbhost=127.0.0.1:3306"

          # 5) Create DB if needed and install only if not installed
          docker exec wp bash -lc "$WP db create || true"
          docker exec wp bash -lc "$WP core is-installed || $WP core install --url=http://localhost:8080 --title='CI Site' --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email"

      - name: Start Apache and wait for HTTP 200/302
        run: |
          docker exec wp bash -lc 'apache2ctl -k start'
          for i in {1..120}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ || true)
            if [ "$code" = "200" ] || [ "$code" = "302" ]; then
              echo "Apache ready ($code)"; break
            fi
            echo "Waiting for Apache... HTTP $code"
            sleep 1
          done

      - name: Copy theme into container (repo root -> ai-news-hub)
        run: |
          docker exec wp bash -lc 'rm -rf /var/www/html/wp-content/themes/ai-news-hub'
          docker cp . wp:/var/www/html/wp-content/themes/ai-news-hub

      - name: Activate theme
        run: docker exec wp /usr/local/bin/wp theme activate ai-news-hub --allow-root --path=/var/www/html

      - name: Register Articles CPT via mu-plugin
        run: |
          docker exec wp /bin/bash -lc 'mkdir -p /var/www/html/wp-content/mu-plugins && cat >/var/www/html/wp-content/mu-plugins/ai-news-hub-cpt.php <<PHP
          <?php
          add_action("init", function () {
            register_post_type("article", array(
              "labels" => array("name" => "Articles","singular_name" => "Article"),
              "public" => true,
              "has_archive" => true,
              "show_in_rest" => true,
              "rest_base" => "articles",
              "supports" => array("title","editor","excerpt","thumbnail"),
              "taxonomies" => array("post_tag"),
              "rewrite" => array("slug" => "articles"),
            ));
          });
          PHP'

      - name: Flush permalinks
        run: |
          docker exec wp /usr/local/bin/wp rewrite structure '/%postname%/' --hard --allow-root --path=/var/www/html
          docker exec wp /usr/local/bin/wp rewrite flush --hard --allow-root --path=/var/www/html

      - name: Create sample Article
        run: |
          docker exec wp /usr/local/bin/wp post create \
            --post_type=article \
            --post_title="CI Sample" \
            --post_status=publish \
            --allow-root --path=/var/www/html

      - name: Smoke test – homepage
        run: curl -sSf http://localhost:8080 | grep -i "<html"

      - name: Smoke test – Articles archive
        run: curl -sSf http://localhost:8080/articles/ | grep -i "Articles"

      - name: Smoke test – REST
        run: curl -sSf http://localhost:8080/wp-json/wp/v2/articles | grep -i "CI Sample"

      - name: PHP lint (theme)
        run: |
          sudo apt-get update && sudo apt-get install -y php-cli >/dev/null
          find . -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
