name: CI – WordPress Smoke Tests (single container)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/ci-wordpress.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start WordPress (Bitnami all-in-one)
        run: |
          docker run -d --name wp \
            -e WORDPRESS_USERNAME=admin \
            -e WORDPRESS_PASSWORD=admin \
            -e WORDPRESS_EMAIL=admin@example.com \
            -e WORDPRESS_BLOG_NAME="CI Site" \
            -e MARIADB_HOST=localhost \
            -e ALLOW_EMPTY_PASSWORD=yes \
            -p 8080:8080 \
            -p 8443:8443 \
            bitnami/wordpress:latest
          # Wait for the bundled DB and WP to initialize
          for i in {1..120}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ || true)
            if [ "$code" = "200" ] || [ "$code" = "302" ]; then
              echo "WordPress UI ready ($code)"; break
            fi
            echo "Waiting for WordPress service... HTTP $code"
            sleep 2
          done

      - name: Prepare WordPress files (host extract + docker cp)
        run: |
          # Put a clean core tree into the app directory used by Bitnami
          curl -sSL https://wordpress.org/latest.zip -o /tmp/wp.zip
          rm -rf /tmp/wordpress && unzip -q /tmp/wp.zip -d /tmp
          docker exec wp bash -lc 'rm -rf /bitnami/wordpress/*'
          docker cp /tmp/wordpress/. wp:/bitnami/wordpress/

      - name: Install WP-CLI and configure (single container)
        run: |
          # Install wp-cli inside the same container
          curl -sS -L https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /tmp/wp-cli.phar
          docker cp /tmp/wp-cli.phar wp:/usr/local/bin/wp
          docker exec wp bash -lc 'chmod +x /usr/local/bin/wp && /usr/local/bin/wp --version || true'

          # Single-shell idempotent setup
          docker exec wp bash -lc '
            set -e
            WP="/usr/local/bin/wp --allow-root --path=/bitnami/wordpress"

            # The Bitnami image already provisions wp-config and DB.
            # Recreate config for consistency, using internal DB on localhost.
            rm -f /bitnami/wordpress/wp-config.php
            $WP config create --dbname=bitnami_wordpress --dbuser=bn_wordpress --dbpass="$(cat /opt/bitnami/wordpress/wp-config.php 2>/dev/null | grep DB_PASSWORD || true)" --dbhost=localhost:3306 || true

            # Ensure install
            $WP core is-installed || $WP core install \
              --url=http://localhost:8080 \
              --title="CI Site" \
              --admin_user=admin \
              --admin_password=admin \
              --admin_email=admin@example.com \
              --skip-email
          '

      - name: Copy theme into container (repo root -> ai-news-hub)
        run: |
          docker exec wp bash -lc 'rm -rf /bitnami/wordpress/wp-content/themes/ai-news-hub'
          docker cp . wp:/bitnami/wordpress/wp-content/themes/ai-news-hub

      - name: Activate theme
        run: docker exec wp /usr/local/bin/wp theme activate ai-news-hub --allow-root --path=/bitnami/wordpress

      - name: Register Articles CPT via mu-plugin
        run: |
          docker exec wp /bin/bash -lc 'mkdir -p /bitnami/wordpress/wp-content/mu-plugins && cat >/bitnami/wordpress/wp-content/mu-plugins/ai-news-hub-cpt.php <<PHP
          <?php
          add_action("init", function () {
            register_post_type("article", array(
              "labels" => array("name" => "Articles","singular_name" => "Article"),
              "public" => true,
              "has_archive" => true,
              "show_in_rest" => true,
              "rest_base" => "articles",
              "supports" => array("title","editor","excerpt","thumbnail"),
              "taxonomies" => array("post_tag"),
              "rewrite" => array("slug" => "articles"),
            ));
          });
          PHP'

      - name: Flush permalinks
        run: |
          docker exec wp /usr/local/bin/wp rewrite structure '/%postname%/' --hard --allow-root --path=/bitnami/wordpress
          docker exec wp /usr/local/bin/wp rewrite flush --hard --allow-root --path=/bitnami/wordpress

      - name: Create sample Article
        run: |
          docker exec wp /usr/local/bin/wp post create \
            --post_type=article \
            --post_title="CI Sample" \
            --post_status=publish \
            --allow-root --path=/bitnami/wordpress

      - name: Smoke test – homepage
        run: curl -sSf http://localhost:8080 | grep -i "<html"

      - name: Smoke test – Articles archive
        run: curl -sSf http://localhost:8080/articles/ | grep -i "Articles"

      - name: Smoke test – REST
        run: curl -sSf http://localhost:8080/wp-json/wp/v2/articles | grep -i "CI Sample"

      - name: PHP lint (theme)
        run: |
          sudo apt-get update && sudo apt-get install -y php-cli >/dev/null
          find . -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
