name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - "!.github/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List workspace
        run: |
          pwd
          echo "--- root ---"
          ls -la
          echo "--- inc ---"
          ls -la inc || true
          echo "--- assets ---"
          ls -la assets || true
          echo "--- react ---"
          ls -la react || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (scp)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          # Include concrete theme paths first (so tar is never empty), then exclude globs.
          source: |
            ./
            !.git/**
            !**/node_modules/**
            !**/src/**
            !**/.vite/**
            !**/coverage/**
            !**/*.map
          target: /ai-news-hub
          overwrite: true

 