name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (wlixcc)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}            # us-east-1.sftpcloud.io
          username: ${{ secrets.SFTP_USER }}          # user-a
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          local_path: "."                             # repo root
          remote_path: "/ai-news-hub"                 # folder inside sftpcloud home
          delete_remote_files: false
          sftp_only: true
          sftpArgs: "-o StrictHostKeyChecking=no"

