name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: sftp
          port: ${{ secrets.SFTP_PORT || '22' }}
          local-dir: .
          server-dir: /ai-news-hub
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            .github/**
            node_modules/**
            **/.DS_Store
