name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - "!.github/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List workspace
        run: |
          pwd
          ls -la

      - name: Upload via SFTP (rsync-like)
        uses: wangyucode/sftp-upload-action@v1.6
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          localDir: ./
          remoteDir: /ai-news-hub/
          log-level: verbose
          exclude: |
            .git/**
            .github/**
            **/.DS_Store
            **/node_modules/**
            react/**
            **/src/**
            **/.vite/**
            **/coverage/**
            **/*.map

