name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.php"
      - "style.css"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # SamKirkland action supports SFTP and does not attempt remote exec
      - name: Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: sftp
          port: ${{ secrets.SFTP_PORT || '22' }}
          # local project root (your theme files live at the repo root)
          local-dir: .
          # sftpcloud default home is / (chroot). Choose a folder you can see/write.
          # If you want a subfolder, it will be created automatically:
          server-dir: /ai-news-hub
          # Set to false so we only upload/overwrite changed files
          dangerous-clean-slate: false
          # Speed up uploads; ignore Git metadata
          exclude: |
            **/.git*
            .github/**
            node_modules/**
            
