name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - "!.github/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List workspace
        run: |
          pwd
          ls -la

      - name: Deploy via SFTP
        uses: SamKirkland/SFTP-Deploy-Action@2fd1f2b4a4c2a7f8c2f6e6f8a8e9a9f1a7b2e5c
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          local-path: ./            # repo root
          remote-path: /ai-news-hub
          ignore: |
            .git/**
            **/node_modules/**
            **/src/**
            **/.vite/**
            **/coverage/**
            **/*.map
