name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - "!.github/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (lftp mirror)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          protocol: sftp
          localDir: .
          remoteDir: /ai-news-hub
          # lftp exclude patterns (space-separated or newline with backslashes)
          exclude: |
            .git/
            **/.DS_Store
            **/node_modules/
            **/src/
            **/.vite/
            **/coverage/
            **/*.map
          options: --verbose --only-newer
 