name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - "!.github/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (atmoz/sftp-deploy)
        uses: atmoz/sftp-deploy@v2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local-dir: .
          remote-dir: /ai-news-hub
          exclude: |
            **/.git/**
            **/.DS_Store
            **/node_modules/**
            **/src/**
            **/.vite/**
            **/coverage/**
            **/*.map
