name: Deploy Theme via SFTP (sftpcloud)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "wp-content/themes/ai-news-hub/**"
      - ".github/workflows/deploy-sftp.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (wlixcc)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          local_path: "wp-content/themes/ai-news-hub"
          remote_path: "/ai-news-hub"
          delete_remote_files: false
          sftp_only: true
          sftpArgs: "-o StrictHostKeyChecking=no"
          # wlixcc expects a single string for exclude, not a YAML sequence
          # exclude react/headlines/node_modules sources (**/node_modules/** below) (built files live in assets/)
          exclude: >
            **/.git/**,
             **/.DS_Store,
            **/node_modules/**,  
            **/src/**,
            **/.vite/**,
            **/coverage/**,
            **/*.map
 