name: Build and Release AI-News Theme artifact (filtered)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Build the same filtered directory used by SFTP workflow
      - name: Prepare deploy directory (same excludes as SFTP)
        run: |
          set -e
          THEME_SRC="./"
          DEPLOY_DIR="deploy"
          mkdir -p "$DEPLOY_DIR"
          rsync -a --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".DS_Store" \
            --exclude "**/node_modules/" \
            --exclude "**/.vite/" \
            --exclude "**/dist/" \
            --exclude "**/coverage/" \
            --exclude "**/*.map" \
            --exclude "react/" \
            --exclude "**/src/" \
            "$THEME_SRC"/ "$DEPLOY_DIR"/
          echo "Deploy dir contents preview:"
          find "$DEPLOY_DIR" -maxdepth 2 -type d -print

      # 2) Validate WordPress theme header exists inside deploy/ (style.css)
      - name: Validate theme header
        run: |
          test -f "deploy/style.css"
          grep -E "Theme Name:" "deploy/style.css"

      # 3) Zip exactly the filtered directory
      - name: Create ZIP from deploy
        run: |
          cd deploy
          zip -r ../ai-news-hub-theme.zip .
          cd ..
          sha256sum ai-news-hub-theme.zip | tee ai-news-hub-theme.zip.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-build
          path: |
            ai-news-hub-theme.zip
            ai-news-hub-theme.zip.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: theme-build
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: "AI News Hub Theme ${{ github.event.inputs.version || github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/ai-news-hub-theme.zip
            dist/ai-news-hub-theme.zip.sha256
