name: Build and Release Theme

permissions:
  contents: write
  
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Verify style.css exists in the repo root and has a Theme header
      - name: Validate theme header
        run: |
          test -f "style.css"
          grep -E "Theme Name:" "style.css"

      # Create a zip of the theme from the repo root
      - name: Create ZIP
        run: |
          zip -r theme.zip .
      
      - name: Checksums
        run: sha256sum theme.zip | tee theme.zip.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-build
          path: |
            theme.zip
            theme.zip.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: theme-build
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: "AI News Hub Theme ${{ github.event.inputs.version || github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/theme.zip
            dist/theme.zip.sha256
